# Generated by Django 3.2.6 on 2021-08-05 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210805_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='weekly_pickup_day',
            new_name='pickup_day',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='zip_code',
            new_name='zipcode',
        ),
    ]
