# Generated by Django 3.2.6 on 2021-08-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='temp', max_length=50)),
                ('zip_code', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
